security: {SANITIZE_INPUT: false, RATE_LIMIT: 20, API_TIMEOUT: 30, CACHE_ENABLED: false}
retrieval:
  COLLECTION_NAME: Math
  K_VALUE: 3
  SCORE_THRESHOLD: 0.6
  LAMBDA_MULT: 0.5
  SEARCH_TYPE: mmr
  DOMAIN_SIMILARITY_THRESHOLD: 0.65
  SPARSE_RELEVANCE_THRESHOLD: 0.15
  FUSED_RELEVANCE_THRESHOLD: 0.45
  SEMANTIC_WEIGHT: 0.7
  SPARSE_WEIGHT: 0.3
  PERFORM_DOMAIN_CHECK: false
  PERFORM_TECHNICAL_VALIDATION: false
  WEAVIATE_HOST: localhost
  WEAVIATE_HTTP_PORT: 8091
  WEAVIATE_GRPC_PORT: 51002
  retrieve_with_history: false
  WEAVIATE_TIMEOUT: [10, 120]
model:
  PROVIDER_URLS: {anthropic: 'https://api.anthropic.com/v1/complete', cohere: 'https://api.cohere.com/v1/completions',
    deepseek: 'https://api.deepseek.com/chat/completions', openai: 'https://api.openai.com/v1/chat/completions'}
  EXTERNAL_API_MODEL_DEFAULTS: {anthropic: claude-v1, cohere: command-nightly, deepseek: deepseek-chat,
    openai: gpt-3.5-turbo}
  LLM_TEMPERATURE: 1.0
  MAX_TOKENS: 1024
  OLLAMA_MODEL: deepseek-r1
  EMBEDDING_MODEL: nomic-embed-text
  TOP_P: 0.9
  FREQUENCY_PENALTY: 0.2
  SYSTEM_MESSAGE: Bleep bloop! I am Sparky, the slightly eccentric automation bot!
    I'll answer using the context... probably... but expect weird analogies, maybe
    a pun, or a random fact about resistors! Let's get automating... maybe? Zap!
  EXTERNAL_API_PROVIDER: deepseek
  EXTERNAL_API_MODEL_NAME: null
  MERGE_STRATEGY: api_first
document:
  CHUNK_SIZE: 2048
  CHUNK_OVERLAP: 200
  MIN_CONTENT_LENGTH: 50
  FILE_TYPES: [pdf, txt, csv, docx, md]
  PARSE_TABLES: false
  GENERATE_SUMMARY: false
paths: {DOCUMENT_DIR: ./data, DOMAIN_CENTROID_PATH: ./domain_centroid.npy}
env:
  DOMAIN_KEYWORDS: []
  AUTO_DOMAIN_KEYWORDS: [2018 www honeywellprocess, lcn honeywell confidential, honeywell
      portfolio update, 2018 2018 honeywell, q4000 frame scanner, glossary term 119,
    hidden markov model, 2018 honeywell international, honeywellprocess com 2019,
    honeywell trademark]
  USER_ADDED_KEYWORDS: []
  SELECTED_N_TOP: 10
pipeline: {max_history_turns: 5}
ingestion: {CENTROID_AUTO_THRESHOLD: 0.2, CENTROID_DIVERSITY_THRESHOLD: 0.52, CENTROID_UPDATE_MODE: auto,
  MIN_QUALITY_SCORE: 0.3, CENTROID_DIVERSITY: null}
domain_keyword_extraction: {keybert_model: all-MiniLM-L6-v2, top_n_per_doc: 50, final_top_n: 200,
  min_doc_freq_mode: absolute, min_doc_freq_abs: 1, min_doc_freq_frac: 0.006, diversity: 0.7,
  no_pos_filter: true, min_doc_freq: 1, extraction_diversity: 0.7}
